name: delta_scheduler
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  async: ^2.8.2
  flutter:
    sdk: flutter
  venice_core:
    git: https://github.com/Venice-D2D/venice_core.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  uuid: ^3.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
